apiVersion: v1
kind: Service
metadata:
  name: goalbasedmvc
  labels:
    app: goalbasedmvc  
spec:
  type: NodePort
  selector:
    app: goalbasedmvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  
# apply: kubectl apply -f deploy/pods/service-only.yaml

